config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  resources :users, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: %i[index show] do
    resources :messages, only: :create
    resources :participations, only: :create
    resources :materials, only: :create
    collection do
      get 'search', to: 'events#search'
    end
  end

  resources :participations, only: %i[index destroy]
  resources :sites, only: :update
end

app/models/participation.rb
# frozen_string_literal: true

class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/participations_controller.rb
# frozen_string_literal: true

class ParticipationsController < ApplicationController
  before_action :set_event, only: %i[create]
  before_action :set_participation, only: %i[destroy]

  def index
    @participations = current_user.participations
  end

  def create
    @participation = Participation.new(participation_params)
    @participation.user = current_user
    @participation.event = @event
    @participation.save!
    redirect_back(fallback_location: request.referer)
  end

  def destroy
    @participation.destroy!
    redirect_to participations_path
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_participation
    @participation = Participation.find(params[:id])
  end

  def participation_params
    if params[:participation_form].nil?
      telescope = vehicle = false
    else
      telescope = params[:participation_form][:telescope] == "on"
      vehicle = params[:participation_form][:vehicle] == "on"
    end
    { material: { telescope: telescope, vehicle: vehicle } }
  end
end

app/views/participations/index.html.erb
<!-- àçéèêîïôü -->
<div class="container">
  <h1>Mes événements à venir</h1>
  <table>
    <thead>
      <th>Date</th>
      <th>Lieu</th>
      <th>Note</th>
      <th>Actions</th>
    </thead>
    <tbody>
      <% @participations.each do |participation| %>
        <tr>
          <td><%= participation.event.date.strftime('%d-%m-%Y') %></td>
          <td><%= participation.event.site.address %></td>
          <td><%= participation.event.score['total_score'] %></td>
          <td>
            <%= link_to event_path(participation.event) do %>
              <i class="far fa-eye" style="font-size: 24px"></i>
            <%end%>
            <%= link_to participation_path(participation), method: :delete, data: { confirm: "Supprimer votre participation à cet événement" } do %>
              <i class="far fa-trash-alt" style="font-size: 24px"></i>
            <%end%>
          </td>
        </tr>
      <% end  %>
    </tbody>
  </table>
</div>