config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  resources :users, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: %i[index show] do
    resources :messages, only: :create
    resources :participations, only: :create
    resources :materials, only: :create
    collection do
      get 'search', to: 'events#search'
    end
  end

  resources :participations, only: %i[index destroy]
  resources :sites, only: :update
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="">
<!--     ⓒ  2019 Astronight, Inc. All Rights Reserved -->
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="brand" style="display: flex; align-items: center;">
    <div>
      <%= link_to root_path, class: "navbar-brand no-margin-top animation-logo" do %>
        <%= image_tag "logo_astronight.png" %>
        <% end %>
    </div>
  <%= link_to root_path, class: "navbar-brand name_margin no-margin-top" do %>
    <h2 class="astronight_name">
      <span>AstroNight</span>
    </h2>
    <% end %>
  </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="display: flex; align-items: center;">
      <% if user_signed_in? %>
        <li>
          <p class="bonjour">Bonjour <%= current_user.username %> </p>
        </li>
        <li  class="nav-item dropdown">
          <%= image_tag current_user.avatar_url, class: "avatar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Mes évènements à venir", participations_path , class: "dropdown-item" %>
            <%= link_to "Mes sites préférés", '#', class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <span class="nav-connexion">
          <%= link_to "Se connecter", new_user_session_path, class: 'btn-bc-light' %>
          <%= link_to "S'inscrire", new_user_registration_path, class: 'btn-bc-light' %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_other.html.erb
<div class="navbar_white navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div style="display: flex; align-items: center;">
    <div>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo_astronight_blue.png" %>
        <% end %>
    </div>
  <%= link_to root_path, class: "navbar-brand name_margin" do %>
    <h2 class="astronight_name_blue">
      <span>AstroNight</span>
    </h2>
    <% end %>
  </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="display: flex; align-items: center;">
      <% if user_signed_in? %>
        <li>
          <p class="bonjour_blue">Bonjour <%= current_user.username %> </p>
        </li>
        <li  class="nav-item dropdown">
          <%= image_tag current_user.avatar_url, class: "avatar_blue", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Mes évènements à venir", '#' , class: "dropdown-item" %>
            <%= link_to "Mes sites préférés", '#', class: "dropdown-item" %>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <span class="nav-connexion">
          <%= link_to "Se connecter", new_user_session_path, class: 'btn-bc-light' %>
          <%= link_to "S'inscrire", new_user_registration_path, class: 'btn-bc-light' %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</div>