config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  resources :users, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: %i[index show] do
    resources :messages, only: :create
    resources :participations, only: :create
    resources :materials, only: :create
    collection do
      get 'search', to: 'events#search'
    end
  end

  resources :participations, only: %i[index destroy]
  resources :sites, only: :update
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :site
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  has_many :messages, dependent: :destroy

  def score_pollution
    rand(100)
  end

  def score_cloud
    rand(100)
  end

  def score_events
    rand(80..100)
  end

  def score_lune
    rand(70..100)
  end

  scope :order_by_total_score, -> {
    order("score ->>'total_score' DESC")
  }
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  require "uri"
  skip_before_action :authenticate_user!
  before_action :set_event, only: :show
  before_action :set_icons, only: %i[show search]

  def index
    @my_events = current_user.events
  end

  def search
    search_params = search_form_params.merge(
      end_date: end_date(params[:searchform][:date_range])
    )
    @events = filter_events(search_params).order_by_total_score
    set_markers_for_search
  end

  def show
    @message = Message.new
    @messages = @event.messages
    @participation = Participation.new
    @small_map = true
    set_markers_for_show
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def start_date
    @start_date ||= Time.zone.today
  end

  def filter_events(search_params)
    if search_params[:address].blank?
      Event.where(
        date: start_date..search_params[:end_date]
      )
    else
      Event.where(
        date: start_date..search_params[:end_date],
        site_id: Site.near(*search_params.slice(:address, :radius).values)
                     .map(&:id)
      )
    end
  end

  def end_date(date_range)
    case date_range
    when "Aujourd'hui" then Time.zone.today
    when "7 prochains jours" then start_date + 7
    when "14 prochains jours" then start_date + 14
    end
  end

  def set_icons
    @icons = {
      base: helpers.asset_url("pin_base.png"),
      selected: helpers.asset_url("pin_selected.png")
    }
  end

  def set_markers_for_search
    @markers = @events.map do |event|
      {
        lat: event.site.lat,
        lng: event.site.lng,
        infoWindow: render_to_string(partial: "infowindow",
                                     locals: { event: event }),
        unique_id: event.id
      }
    end
  end

  def set_markers_for_show
    @markers = [
      {
        lat: @event.site.lat,
        lng: @event.site.lng,
        image_url: helpers.asset_url("map-marker.png")
      }
    ]
  end

  def search_form_params
    params[:searchform][:radius] = params[:searchform][:radius].tr("km", "").to_i
    params.require(:searchform).permit(:address, :date_range, :radius)
  end
end

app/views/events/_details.html.erb
<div 1 class="div_generale">
  <div 2 class="div_haut">
    <div 4 class="div_haut_gauche">
      <div 6 class="div_lieu">
        <h4><b><%= @event.site.address %></b></h4>
      </div>
      <div 7 class="div_date">
        <h5><span id="event" data-date=<%= @event.date %>><%= I18n.localize(@event.date, format: :custom) %></span></h5>
      </div>
    </div>
    <div 5 class="div_haut_droite">
      <div 16 class="div_btn_confirmation">
        <% if current_user.nil? %>
          <% user_events = [] %>
        <% else %>
          <% user_events = current_user.participations.map {|part| part.event_id} %>
        <% end %>

        <% if user_events.include?(@event.id) %>
          <%= link_to "https://www.google.com/calendar/render?action=TEMPLATE&text=#{URI.encode("Soirée Astronomie")}&dates=#{@event.date.strftime('%Y%m%dT180000')}/#{(@event.date + 1.days).strftime('%Y%m%dT030000')}&location=#{@event.site.address}&sprop=name:Name&sprop=website:EventWebite&details=#{@event.site.description}&sf=true&output=xml", class: 'calendar_btn btn-show je_participe',target: "_blank" do %>
          Ajouter à mon calendrier
        <% end %>
        <% elsif user_signed_in? %>
          <button class='btn-show je_participe' id= 'modal-toggle' name='commit' data-toggle='modal' data-target='#confirmModal' data-disable-with="Je participe !">Participer</button>
        <% end %>
      </div>
    </div>
  </div>
  <div 2 class="div_haut">
    <div 13 class="div_score">
      <h3>Analyse des conditions d'observation</h3>
      <p>Note du soir</p>
      <div id="mygauge" style="text-align:right; margin:0px auto 0px auto;" class="cpuSpeed gauge-container" data-score="<%= @event.score["total_score"] %>">
      </div>
      <div class="affichage">
        <div id="cloud-score" data-score=<%= @event.score["cloudiness_score"]%> style="text-align: center;"><p><i class="fas fa-cloud-sun cloud-sun fa-lg"></i> <%= @event.score["cloudiness_score"] %>/10 <br>  Prévision météo</p>
        </div>
        <div id="pol-score" data-score=<%= @event.score["light_pol_score"] %> style="text-align: center;"><p><i class="fas fa-city city fa-lg"></i> <%= @event.score["light_pol_score"] %>/10 <br> Pollution lumineuse</p>
        </div>
        <div id="astro-score" data-score=<%= @event.score["astro_event_score"] %> style="text-align: center;"><p><i class="fas fa-eye eye fa-lg"></i> <%= @event.score["astro_event_score"] %>/10 <br> Evènements astronomiques</p></div>
        <div id="moon-score" data-score=<%= @event.score["moon_score"] %> style="text-align: center;"><p><i class="fas fa-moon moon fa-lg"></i> <%= @event.score["moon_score"] %>/10 <br> Luminosité Lune</p>
        </div>
      </div>
    </div>
  </div>
  <div 3 class="div_bas">
    <div 9 class="div_bas_gauche">
      <div 12 class="div_participants">
        <h3>Participants</h3>
        <br>
        <%= render 'participations_table' %>
      </div>
    </div>
    <div 8 class="div_bas_droite">
      <div 10 class="div_photo">
        <div class="show_photo"><%= image_tag @event.site.photo, class: 'show_photo' %></div>
      </div>
      <div 11 class="div_description">
        <h7><i><%= @event.site.description %></i></h7>
      </div>

      <div 5 bis class="div_bas_btn">
        <div 16 class="div_btn_confirmation">
          <%= render 'mapbox' %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'toolmodal' %>

app/views/events/_discussion.html.erb
<div class="messagerie">
  <div class="center-div">
    <h3 class="text-center">Discussion</h3>
    <div class="jumbotron zone_messages" style="padding: 0">

      <div class="well p-3 center" id="chatbox" style="height:320px; overflow-y: scroll">
        <% @messages.each do |message|%>
          <%= render 'messages/message', message: message %>

        <% end  %>
      </div>
      <%= form_with url: event_messages_path(@event),remote: true do |f| %>
        <div class="input-group mb-3">
          <%= f.text_field :body, label: false, placeholder: 'Postez votre message ici...', class: 'form-control input-messagerie' %>
          <div class="input-group-append">
            <%= f.submit "Envoyez", class: "btn-messagerie" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_infowindow.html.erb
<%= link_to "#{event.site.address} le #{event.date.strftime("%d/%m")}" , event_path(event) %>
 (<%= event.score %>/10)

app/views/events/_mapbox.html.erb
<% thisclass = nil %>
<% thisclass = "map2" if @small_map %>

<div
  id="map"
  class="<%= thisclass %>"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="pk.eyJ1Ijoic2lydGF5bG9yODgiLCJhIjoiY2p2N3ppaTI0MDFzZzQ2bW01MmZ2MGFhbCJ9.qbFjjsDDBjZKLpOCwWIpyg"
  data-icons="<%= @icons.to_json %>"
></div>

app/views/events/_moonphase.html.erb
<div id="contain_moon" style="text-align:center;padding-bottom:5px;">
  <div style="font-weight:bold"></div>
  <div>.</div>
  <div style="font-size:small">
  </div>
</div>


<script type="text/javascript">
  eventDate = document.querySelector('#event').dataset.date
  const month = Number.parseInt(eventDate.split('-')[1]);
  const day = Number.parseInt(eventDate.split('-')[2]);
  const year = Number.parseInt(eventDate.split('-')[0]);

  (function(){
    const d = Number.parseInt(eventDate.split('-')[2])
    const m = document.querySelectorAll("#contain_moon div");
    const a = new XMLHttpRequest();
    const url = "http://www.icalendar37.net/lunar/api/?lang=fr&month="+ month + "&year=" + year + "&size=100&lightColor=rgb(255,255,255)&shadeColor=rgb(17,17,17)&LDZ="+ new Date(new Date().getFullYear(), month - 1,1)/1000 + "";
    m[1].style.height="100px";
      a.onreadystatechange=function(){
        if(a.readyState == 4 && a.status == 200) {
          var b = JSON.parse(a.responseText);
          m[1].innerHTML = b.phase[d].svg;
          if (typeof moon_widget_loaded=="function") moon_widget_loaded(b);
          m[2].innerHTML = b.phase[d].npWidget
        }
        };
          a.open("GET",url,true);a.send()})()
</script>

app/views/events/_obs_info_table.html.erb
<table>
  <tbody>
    <tr>
      <th>Light pollution index</th>
      <td><%= @event.site.light_pol_index %>/20</td>
    </tr>
    <tr>
      <th>Temps</th>
      <td></td>
    </tr>
    <tr>
      <th>Nébulosité (<em>en %</em>)</th>
      <td></td>
    </tr>
    <tr>
      <th>Humidité (<em>en %</em>)</th>
      <td></td>
    </tr>
    <tr>
      <th>Vitesse de vent (<em>en km/h</em>)</th>
      <td></td>
    </tr>
  </tbody>
</table>

app/views/events/_observation.html.erb
<div class="d-flex flex-column bd-highlight my-3">

  <div class="p-2 bd-highlight" name="Meteo">
      <div class="d-flex justify-content-start align-self-center mb-3" name="MeteoTitle">
        <div class="fas fa-cloud-sun fa-2x ml-2"></div>
        <% weather = @event.site.next_5_days_meteo.find {|weather_night| weather_night['night'] == @event.date.strftime('%d-%m-%Y')}  %>

        <h3 class="ml-3">Météo de la soirée du <%= I18n.localize(@event.date, format: :custom) %></h3>
        <h3 class="badge"><%= @event.score["cloudiness_score"] %>/10 </h3>
      </div>
      <div class="row justify-content-center">
        <% weather['weathers'].each do |weather_hour| %>
        <div class="col-3 p-3 text-center">
          <div class="col-12 border p-3">
            <h4><strong><%= weather_hour['time'] %></strong></h4>
          </div>
          <div class="col-12 border p-3">
            <br>
            <pre><h4><%= image_tag image_url('cloud.svg'), size: '32x32' %> <%= weather_hour['cloudiness'] %>%</h4></pre>
            <pre><h4><%= image_tag image_url('humidity.svg'), size: '32x32' %> <%= weather_hour['humidity'] %>%</h4></pre>
            <pre><h4><%= image_tag image_url('wind.svg'), size: '32x32' %> <%= (weather_hour['wind_speed_ms'] * 3.6).floor %> km/h</h4></pre>
          </div>
        </div>
        <% end  %>
      </div>
  <hr>
  </div>

  <div class="p-2 bd-highlight" name="PollutionLumineuse">
    <div class="d-flex justify-content-start align-self-center mb-3" name="PollTitle">
      <div class="fas fa-city fa-2x ml-2"></div>
      <h3 class="ml-3">Pollution Lumineuse</h3>
      <h3 class="badge"><%= @event.score["light_pol_score"] %>/10</h3>
    </div>
    <p class="font-italic">La pollution lumineuse est la conséquence de l'éclairage artificiel nocturne des villes. Elle nuit à l'observation astronomique en créant un brouillard lumineux quasi-permanent.</p>
    <iframe src="<%= "https://darksitefinder.com/maps/world.html#9/#{@event.site.lat}/#{@event.site.lng}" %>" name="targetframe" allowTransparency="true" scrolling="yes" frameborder="0" style="width: 100%;height: 70vh" >
    </iframe>
  <hr>
  </div>

  <div class="p-2 bd-highlight" name="Lune">
    <div class="d-flex justify-content-start align-self-center mb-3" name="MoonTitle">
      <div class="fas fa-moon fa-2x ml-2"></div>
      <h3 class="ml-3">Phase lunaire</h3>
      <h3 class="badge"><%= @event.score["moon_score"] %>/10</h3>
    </div>
     <p class="font-italic mb-3">Les cycles de la lune ont une incidence sur la qualité des observations astronomique. La lune reflète intensément la lumière du Soleil et si sa phase dépasse le croissant, elle peut devenir une source d'éclairage du ciel aussi gênante que la pollution lumineuse urbaine.</p>
    <%= render 'moonphase' %>
  <hr>
  </div>

  <div class="p-2 bd-highlight" name="AstroEvent">
    <div class="d-flex justify-content-start align-self-center mb-3" name="AstroTitle">
      <div class="fas fa-eye fa-2x ml-2"></div>
      <h3 class="ml-3">Evénements Astronomiques</h3>
      <h3 class="badge"><%= @event.score["astro_event_score"] %>/10</h3>
    </div>
     <p class="font-italic mb-2">Les observations astronomiques sont ponctuées d'evènements et phénomènes qui se produisent à fréquence variable et rendent mémorables vos sorties.</p>
     <span id="event" data-date="2019-06-11" 00:00:00="" utc=""><%= I18n.localize(@event.date, format: :custom) %></span><ul><li>Opposition de Jupiter avec le Soleil: Cette configuration correspond aux conditions favorables d'observation de Jupiter. En effet, c'est au moment de l'opposition avec le Soleil que la distance entre Jupiter et la Terre est minimale. La planète se lève peu après le coucher du soleil.</li></ul>
  <hr>
  </div>
</div>

app/views/events/_participations_table.html.erb
<div id="conteneur">
  <div class="row nowrap">
    <% @event.participations.each do |participation| %>
    <div class="wrap">
      <div class="element">
        <%= cl_image_tag participation.user.avatar, gravity: :face, crop: :thumb, radius: :max, width: 80, height: 80, background: "#f6f6f6" %>
      </div>

      <div class="element">
        <%= participation.user.username %>
      </div>

      <div class="element">
        <span style="font-size:smaller">
          Inscrit il y a <%=distance_of_time_in_words(Time.now - participation.created_at) %>
        </span>
      </div>

      <div class="element">
          <% if participation.material["vehicle"] %>
            <i class="fas fa-car-alt"></i>
          <% end %>
          <% if participation.material["telescope"] %>
            <i class="fas fa-binoculars"></i>
          <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/events/_results_cards.html.erb
<div class="flex-item" id="first-ten-items">
  <% @events.each_with_index do |event, index| %>
    <div class="ul-cards">
      <%= link_to event_path(event) do %>
        <div class="card-trip" data-id="<%= event.id %>" id="event-<%= index + 1 %>" style="<%= 'display:none' if index > 9 %>">
          <%= image_tag "#{event.site.photo}", class: 'img-radius', style: "background-image: url(#{image_url('image-placeholder-225x225.png')})" %>
          <div class="card-trip-infos">
            <div>
              <h4 class="h4-cards"><%= I18n.localize(event.date, format: :custom) %></h4>
              <p><%= event.site.address %></p>
            </div>
            <div>
              <div><p style="text-align: center; font-size: 16px">Note du soir</p></div>
              <!-- Gauge chart -->
              <div id="mygauge" class="cpuSpeed gauge-container" data-score=<%= event.score["total_score"] %>></div>
              <!-- End of gauge chart -->
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<button id="show-more" style="float:right; margin-right:64px" data-count="0" data-max="<%= @events.count %>">Plus de résultats</button>

app/views/events/_skymap.html.erb
<div class="d-flex flex-column bd-highlight my-3">

  <div class="p-2 bd-highlight" name="Meteo">
      <div class="d-flex justify-content-start align-self-center mb-3" name="MeteoTitle">
        <div class="fas fa-star fa-2x ml-2"></div>
        <h3 class="ml-3">Carte du ciel pour la soirée du <%= I18n.localize(@event.date, format: :custom) %></h3>
      </div>
    <p class="font-italic mb-3">Pour mieux préparer votre sortie, vous pouvez avoir un aperçu interactif des étoiles et objets célestes qui seront visibles cette nuit-là.</p>
      <div class="outerstellarium">
        <div class="black-square"><%= I18n.localize(@event.date, format: :custom) %></div>
        <iframe id="innerstellarium" src="https://stellarium-web.org/" border="0"></iframe>
      </div>
  <hr>
  </div>

app/views/events/_toolmodal.html.erb
<div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmModalLabel">Votre présence est confirmée !</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        Pour assurer une soirée réussie, vous pouvez mettre à disposition certains éléments aux autres participants:
        <%= simple_form_for :participation_form, url: event_participations_path(@event) do |f| %>
      <!-- checkboxes -->
        <div class="checkboxes">
          <section class="light-bg">
            <span>J'apporte mon téléscope</span>
            <%= f.input :telescope, label: false, input_html: {class:"toggle toggle__light", type: 'checkbox'} %>
          </section>
          <section class="light-bg">
            <span>Je partage ma voiture</span>
            <%= f.input :vehicle, label: false, input_html: {class:"toggle toggle__light", type: 'checkbox'} %>
          </section>
        </div>
      </div>
      <!-- end of checkboxes -->

      <div class="modal-footer">
        <%= f.button :submit, "Enregistrer", class: "btn btn-show" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<table>
  <thead>
    <th>Index</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <% @my_events.each_with_index do |ev, index|%>
  <tbody>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= ev.date.strftime("%d/%m/%Y") %></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/events/search.html.erb
<% content_for :body_class, 'has-loader' %>

<div>
  <div class="container">
    <div class="container p-3" style="color: white">
      <!-- <div class="loader">
        <div class="star star-1"></div>
        <h3>Analyse des conditions d'observation...</h3>
        <br>
        <br>
        <h2 id="countup-site"></h2>
        <h2 id="countup-light-pol"></h2>
        <h2 id="countup-meteo"></h2>
        <h2 id="countup-astro-events"></h2>
      </div> -->
      <br>
      <div class="flex-container">
        <div>
          <h3 class= "text-center search-title">
            Nous vous recommandons <br> ces <%= @events.count %> événements :
          </h3>
          <%= render 'results_cards' %>
        </div>
        <div class="flex-item mapbox">
          <%= render 'mapbox' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container show-no-margin from_reserv">
  <br>
  <div>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a href="#details" class="nav-link active" role="tab" data-toggle="tab">Détails</a>
      </li>
      <li class="nav-item">
        <a href="#messages" class="nav-link" role="tab" data-toggle="tab">Messages</a>
      </li>
      <li class="nav-item">
        <a href="#conditions" class="nav-link" role="tab" data-toggle="tab">Conditions d'observation</a>
      </li>
      <li class="nav-item">
        <a href="#skymap" class="nav-link" role="tab" data-toggle="tab">Carte du Ciel</a>
      </li>
    </ul>
  </div>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in show active" id="details">
      <%= render 'details'%>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="messages">
      <%= render 'discussion'%>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="conditions">
      <%= render 'observation'%>
    </div>
     <div role="tabpanel" class="tab-pane fade " id="skymap">
      <%= render 'skymap'%>
     </div>
  </div>
</div>