config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  root to: 'pages#home'
  resources :users, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: %i[index show] do
    resources :messages, only: :create
    resources :participations, only: :create
    resources :materials, only: :create
    collection do
      get 'search', to: 'events#search'
    end
  end

  resources :participations, only: %i[index destroy]
  resources :sites, only: :update
end

app/views/pages/_searchform.html.erb
  <%= simple_form_for :searchform, url: search_events_path, method: "GET" do |f| %>
      <p class="mb-0">Où ?</p>
    <div class="form-inline align-items-center">
      <div><%= f.input :address, label: false, input_html: { placeholder: 'Entrez une adresse', size: 42 } %></div>
      <div><%= f.input :radius, label: false, collection: %W[50\skm 100\skm 200\skm], selected: '100 km' %></div>
    </div>
    <div class="radio-choices">
      <%= f.input :date_range, label: "Quand ?", required: false,  as: :radio_buttons, collection: ["Aujourd'hui", "7 prochains jours", "14 prochains jours"], checked: "Aujourd'hui"%>
    </div>
    <%= f.button :submit, 'Go !', class: 'btn-bc-go je_participe_home', id: "searchbtn" %>
  <% end %>

app/views/pages/home.html.erb
<div class="banner d-flex flex-column">
  <div class="row align-items-center justify-content-around">
    <div class="col-5 " style="text-align: left;">
      <h1 class="pb-3">Passez vos nuits dehors</h1>
      <p style="font-size: 20px">Astronight vous recommande les meilleurs lieux et dates pour aller observer les plus beaux ciels étoilés<p>
    </div>
    <div class="col-6 text-align-start" style="text-align: left;">
      <%= render 'searchform' %>
    </div>
  </div>
</div>